- name: java-starter-guides playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
  - role: ansible.openshift_raw
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: test

