- src: siamaksade.openshift_sonatype_nexus
  version: 1.1.0
  name: openshift_sonatype_nexus

- src: siamaksade.openshift_gogs
  version: 1.1.0
  name: openshift_gogs

- src: openshift_labs.workshop_deployment_tracker
  version: 1.0.1
  name: workshop_deployment_tracker

- src: git+https://github.com/openshift-homeroom/ansible-labs-deployer
  version: 0.1.0
  name: homeroom_labs_deployer
