---
- name: login as super user with token
  command: "oc login {{ master_url }} --token={{ openshift_token }} --insecure-skip-tls-verify=true"
  when:
    - openshift_token is defined
    - openshift_token is not none
    - openshift_token|trim() != ""

- name: login as super user with pwd
  command: "oc login {{ master_url }} -u {{ openshift_user }} -p {{ openshift_password }} --insecure-skip-tls-verify=true"
  when: >
    openshift_token is not defined or
    openshift_token is none or
    openshift_token|trim() == ""

- name: Verify user can create projects
  command: "oc auth can-i create project"
  register: canicreateprojects
  failed_when: canicreateprojects.stdout != 'yes'
  when: create_projects

- name: Verify user can delete projects
  command: "oc auth can-i delete project"
  register: canideleteprojects
  failed_when: canideleteprojects.stdout != 'yes'
  when: create_projects

