## Lab: Binary Builds for Day to Day Development

### Moving on From S2I
As you saw before S2I is a great way to get from source code to a container, but the process is a bit too slow for daily fast iteration
development. For example, if you want to change some CSS or change one method in a class you don't want to go through
a full git commit and build cycle. In this lab we are going to show you a more efficient method for quick iteration. While
we are at it we will also throw in showing you how to debug your code as well.

Now that we built the MLB parks service let's go ahead and make some quick changes

### Fast Iteration Code Change Using Binary Deploy

The OpenShift command line has the ability to do a deployment from your local machine. In this case we are going to use S2I,
but we are going to tell OpenShift to just take the war file from our local machine and bake it in the image.

Doing this pattern of development let's us do quick builds on our local machine (benefitting from our local cache and
all the horsepower on our machine) and then just quickly send up the war file.

NOTE: You could also use this pattern to actually send up your working directory to the S2I builder to have it do the Maven build
on OpenShift. Using the local directory would relieve you from having Maven or any of the Java toolchain on your local
machine AND would also not require git commit with a push. Read more in the
https://{{DOCS_URL}}/dev_guide/dev_tutorials/binary_builds.html[official documentation]


#### Exercise: Using binary deployment

##### Clone source
The first step is to clone the MLB source code from GitHub to your local machine:

[source,bash,role=copypaste]
----
git clone https://github.com/openshift-roadshow/mlbparks.git
----

NOTE: We are using Intellij here in the guide for screenshots but this should work regardless of your tool chain. JBoss
Developer Studio and JBoss Developer Tools have built in functionality that makes this close to seamless right from the IDE.

##### Setup the Build of the war file
If you have Maven all set up on your machine, then you can just do a:


[source,bash,role=copypaste]
----
mvn package
----

Pay attention to the output location for the ROOT.war, we will need that directory later.

If you're using IntelliJ or eclipse/JBoss Developer Studio package the maven artifact using the IDE.

##### Code Change
Time for a source code change! Go to src/main/java/com/openshift/evg/roadshow/rest/BackendController.java. This is the REST endpoint
that gives basic info on the service and can be reached at:

CAUTION: In the following url(s), replace `userXY` with the guid provided to you.

[source,bash]
----
http://mlbparks-userXY.{{ROUTER_ADDRESS}}/ws/info/
----

Please change line 23 to add a _AMAZING_ in front of "MLB Parks" look like this:

[source,java]
----
return new Backend("mlbparks", "AMAZING MLB Parks", new Coordinates("39.82", "-98.57"), 5);
----

Don't forget to save the file.

#####  Doing the Binary Build

Alright we have our war file built, time to kick off a build using it.

If you built your war with Maven:

[source,bash,role=copypaste]
----
oc start-build bc/mlbparks --from-file=target/ROOT.war --follow
----

NOTE: The --follow is optional if you want to follow the build output in your terminal.

Using labels and a recreate deployment strategy, as soon as we get the new deployment finishes the map name
will be updated. Under a recreate deployment strategy we first tear down the pod before doing our new deployment.
When the pod is torn down, the parksmap service removes the MLBParks map from the layers. When it comes back up, the layer
automatically get's added back with our beautiful new title.  This would not have happened with a rolling deployment because
rolling spins up the new version of the pod before it takes down the old one. Rolling strategy enables a zero-downtime deployment.

When the deployment is finished and the container is deployed you will see the new content at:

CAUTION: In the following url(s), replace `userXY` with the project provided to you.

[source,bash]
----
http://mlbparks-userXY.{{ROUTER_ADDRESS}}/ws/info/
----

So now you have seen how we can speed up the build and deploy process.
