---
id: training
name: Internal training

content:
  url: https://raw.githubusercontent.com/osevg/workshopper-content/master

vars:
  EXPLORE_PROJECT_NAME: ""
  USER_SUFFIX: userXY
  USER_NAME: "(email)"
  USER_PASSWORD: "(email)"
  PARKSMAP_IMAGENAME: "parksmap"
  PARKSMAP_VERSION: "1.2.0"
  PARKSMAP_PY: true
  NATIONALPARKS_VERSION: "1.2.1"
  MLBPARKS_VERSION: "1.0.0"
  DOWNLOAD_CLIENT_WINDOWS: https://github.com/openshift/origin/releases/download/v3.6.0/openshift-origin-client-tools-v3.6.0-c4dd4cf-windows.zip
  DOWNLOAD_CLIENT_MAC: https://github.com/openshift/origin/releases/download/v3.6.0/openshift-origin-client-tools-v3.6.0-c4dd4cf-mac.zip
  DOWNLOAD_CLIENT_LIN64: https://github.com/openshift/origin/releases/download/v3.6.0/openshift-origin-client-tools-v3.6.0-c4dd4cf-linux-64bit.tar.gz
  OC_VERSION: "oc v3.6.0+c4dd4cf\nkubernetes v1.6.1+5115d708d7"
  GIT_HOST: github
  DOCS_URL: docs.openshift.org

modules:
  activate:
  - install
  - explore
  - parksmap-architecture
  - docker
  - scaling
  - routes
  - logging
  - permissions
  - python
  - databases-py
  - application-health
  - codechanges
  - templates
  - further-resources
