---
#####
# Terminals are provided by the hosted workshop template copied from
# github/openshift-labs/workshop-jupyterhub/templates/hosted-workshop-production.json
# We copy it to ../templates/ after each upstream release.
#
# TODO: Use template direct from upstream by -f URL reference and remove from
# this repo.
#####
- name: "Process hosted workshop template"
  template:
    src: hosted-workshop-production.json
    dest: "{{ tmp_dir.path }}/hosted-workshop-production.json"

- name: Add hosted workshop template to {{ namespace }}
  command: "oc apply -f {{ tmp_dir.path }}/hosted-workshop-production.json -n {{ namespace }}"

- name: Generate hosted workshop app manifest
  shell: >
        oc new-app hosted-workshop-production
        -p ADMIN_USERS={{ openshift_user }}
        -p APPLICATION_NAME=terminal
        -n {{ namespace }}
        --dry-run -o json > hosted-workshop-production.json
  args:
    chdir: "{{ tmp_dir.path }}"

- name: Apply hosted workshop manifest to instantiate cluster objects
  command: "oc apply -f hosted-workshop-production.json -n {{ namespace }}"
  args:
    chdir: "{{ tmp_dir.path }}"
