---
#####
# Etherpad
#####
- name: "Copy etherpad base text file"
  copy:
    src: etherpad.txt
    dest: "{{ tmp_dir.path }}/etherpad.txt"

- name: Add {{ user_count }} to etherpad.txt file
  lineinfile:
    path: "{{ tmp_dir.path }}/etherpad.txt"
    line: "{{ item }}"
  with_sequence: start=1 end={{ user_count }} format="{{ user_format }}="

- set_fact:
    etherpad_text: "{{ lookup('file', '{{ tmp_dir.path }}/etherpad.txt') | replace('\n', '\\n')}}"

- name: "Process etherpad template"
  template:
    src: etherpad.yml
    dest: "{{ tmp_dir.path }}/etherpad.yml"

- name: Add etherpad template to {{ namespace }}
  command: "oc apply -f {{ tmp_dir.path }}/etherpad.yml -n {{ namespace }}"

- name: Create install etherpad resources
  shell: >
        oc new-app etherpad --name=etherpad -n {{ namespace }}
        --dry-run -o yaml > etherpad.yml
  args:
    chdir: "{{ tmp_dir.path }}"

- name: Apply etherpad objects
  command: "oc apply -f etherpad.yml -n {{ namespace }}"
  args:
    chdir: "{{ tmp_dir.path }}"