Access to the workshop is provided by link:https:https://github.com/openshift-homeroom[Homeroom], an interactive training environment you can use in your web browser without needing to install anything on your local machine.

The Homeroom dashboard provides you access to the workshop content and one or more terminals. The interactive shells are hosted in a container running inside of OpenShift. Any special command line programs you need are already pre-installed.

As you work through the workshop content you will encounter commands that you need to run in the terminals. These will appear as:

[source,text,role=execute-1]
----
date
----

Where a command appears like this with the play symbol +++<span class="fas fa-play-circle"></span>+++ to the right side of the command, you do not need to type the command into the terminal yourself. Instead, click anywhere on the command and it will be run automatically in the terminal for you.

Try clicking on the above command if you have not done so already.

Use this method of running the commands as it will save you time and avoid mistakes.

Usually the command will be run in the terminal at the top, but in some cases it will be run in the bottom terminal. You do not have to worry about which, the command when clicked will be run where it needs to be.

Try clicking the command below and it should go the terminal at the bottom.

[source,text,role=execute-2]
----
sleep 3600
----

If you encounter a command block showing `<ctrl-c>`, this is treated in a special way:

[source,text,role=execute-2]
----
<ctrl-c>
----

Click on this and you will see that it will send an interrupt to the terminal. You could also have used `<ctrl-c>` yourself in the terminal.

At times, instead of running a command, you may need to copy the value and paste it into the terminal or other web page. This will be indicated using the copy symbol +++<span class="fas fa-copy"></span>+++.

[source,text,role=copy]
----
{{username}}
----

Clicking on the displayed value in this case will copy it into the system paste buffer ready to paste to whatever location the workshop instructions tell you to.

Usually the workshop content will display the correct command or value, even if based on your user name or the name of the project you are using. This is because you will get a personalised version of the workshop content.

If when copying the value, you need to first edit the value before being used, this will be indicated using the user edit symbol +++<span class="fas fa-user-edit"></span>+++.

[source,text,role=copy-and-edit]
----
change-this-to-your-username
----

Clicking on the displayed value will again copy it into the system paste buffer and you can then paste it to the required location. Before the value is used though, you should make any changes as instructed.

How to paste a value into the terminals will depend on the operating system and browser being used. For macOS you should be able to use `<command-v>`. On Linux and Windows, try `<ctrl-v>` or `<ctrl-shift-v>`.

If at any time a glitch occurs and the workshop content does not display properly because of a network issue, and so an error is displayed, or it shows as a white page, select the dropdown hamburger menu top right in the banner above the terminals and select "Reload Workshop". That menu item will reload just the workshop content and leave you on the same page.

Similarly, if the terminals stop working or show as closed, select "Reload Terminal" from the dropdown hamburger menu.

Do not use the ability of the browser to reload the whole browser page as you will loose where you were up to in the workshop content. Also do not use the "Restart Session" menu item unless specifically directed to as you will loose all your work.

If you have any issues which using the reload menu items do not solve, ask the workshop instructor.
