WORKSHOP_NAME=lab-getting-started
WORKSHOP_IMAGE=quay.io/openshiftlabs/lab-getting-started:ocp-4.2
WORKSHOP_TITLE="Getting Started with OpenShift"
WORKSHOP_DESCRIPTION="A workshop introducing developers to OpenShift"
CONSOLE_IMAGE=quay.io/openshift/origin-console:4.2
SPAWNER_PASSWORD=openshift
RESOURCE_BUDGET=medium
MAX_SESSION_AGE=7200
IDLE_TIMEOUT=300
