WORKSHOP_NAME=lab-getting-started
WORKSHOP_IMAGE=quay.io/bluesman/lab-getting-started:ocp-4.4
WORKSHOP_TITLE="Getting Started with OpenShift"
WORKSHOP_DESCRIPTION="A workshop introducing developers to OpenShift"
CONSOLE_IMAGE=quay.io/openshift/origin-console:4.4
RESOURCE_BUDGET=x-large
MAX_SESSION_AGE=7200
IDLE_TIMEOUT=300
SPAWNER_MODE=terminal-server
OPENSHIFT_PROJECT="{username}"
